// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateApplicationRequest(
	name AccountObjectIdentifier,
	PackageName AccountObjectIdentifier,
) *CreateApplicationRequest {
	s := CreateApplicationRequest{}
	s.name = name
	s.PackageName = PackageName
	return &s
}

func (s *CreateApplicationRequest) WithApplicationVersion(ApplicationVersion *ApplicationVersionRequest) *CreateApplicationRequest {
	s.ApplicationVersion = ApplicationVersion
	return s
}

func (s *CreateApplicationRequest) WithDebugMode(DebugMode *bool) *CreateApplicationRequest {
	s.DebugMode = DebugMode
	return s
}

func (s *CreateApplicationRequest) WithComment(Comment *string) *CreateApplicationRequest {
	s.Comment = Comment
	return s
}

func (s *CreateApplicationRequest) WithTag(Tag []TagAssociation) *CreateApplicationRequest {
	s.Tag = Tag
	return s
}

func NewApplicationVersionRequest() *ApplicationVersionRequest {
	return &ApplicationVersionRequest{}
}

func (s *ApplicationVersionRequest) WithVersionDirectory(VersionDirectory *string) *ApplicationVersionRequest {
	s.VersionDirectory = VersionDirectory
	return s
}

func (s *ApplicationVersionRequest) WithVersionAndPatch(VersionAndPatch *VersionAndPatchRequest) *ApplicationVersionRequest {
	s.VersionAndPatch = VersionAndPatch
	return s
}

func NewVersionAndPatchRequest(
	Version string,
	Patch int,
) *VersionAndPatchRequest {
	s := VersionAndPatchRequest{}
	s.Version = Version
	s.Patch = Patch
	return &s
}
