// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateApplicationRequest(
	name AccountObjectIdentifier,
	PackageName AccountObjectIdentifier,
) *CreateApplicationRequest {
	s := CreateApplicationRequest{}
	s.name = name
	s.PackageName = PackageName
	return &s
}

func (s *CreateApplicationRequest) WithVersion(Version *ApplicationVersionRequest) *CreateApplicationRequest {
	s.Version = Version
	return s
}

func (s *CreateApplicationRequest) WithDebugMode(DebugMode *bool) *CreateApplicationRequest {
	s.DebugMode = DebugMode
	return s
}

func (s *CreateApplicationRequest) WithComment(Comment *string) *CreateApplicationRequest {
	s.Comment = Comment
	return s
}

func (s *CreateApplicationRequest) WithTag(Tag []TagAssociation) *CreateApplicationRequest {
	s.Tag = Tag
	return s
}

func NewApplicationVersionRequest(
	VersionDirectory *string,
) *ApplicationVersionRequest {
	s := ApplicationVersionRequest{}
	s.VersionDirectory = VersionDirectory
	return &s
}

func (s *ApplicationVersionRequest) WithVersionAndPatch(VersionAndPatch *VersionAndPatchRequest) *ApplicationVersionRequest {
	s.VersionAndPatch = VersionAndPatch
	return s
}

func NewVersionAndPatchRequest(
	Version string,
	Patch *int,
) *VersionAndPatchRequest {
	s := VersionAndPatchRequest{}
	s.Version = Version
	s.Patch = Patch
	return &s
}

func NewDropApplicationRequest(
	name AccountObjectIdentifier,
) *DropApplicationRequest {
	s := DropApplicationRequest{}
	s.name = name
	return &s
}

func (s *DropApplicationRequest) WithIfExists(IfExists *bool) *DropApplicationRequest {
	s.IfExists = IfExists
	return s
}

func (s *DropApplicationRequest) WithCascade(Cascade *bool) *DropApplicationRequest {
	s.Cascade = Cascade
	return s
}

func NewShowApplicationRequest() *ShowApplicationRequest {
	return &ShowApplicationRequest{}
}

func (s *ShowApplicationRequest) WithLike(Like *Like) *ShowApplicationRequest {
	s.Like = Like
	return s
}

func (s *ShowApplicationRequest) WithStartsWith(StartsWith *string) *ShowApplicationRequest {
	s.StartsWith = StartsWith
	return s
}

func (s *ShowApplicationRequest) WithLimit(Limit *LimitFrom) *ShowApplicationRequest {
	s.Limit = Limit
	return s
}

func NewDescribeApplicationRequest(
	name AccountObjectIdentifier,
) *DescribeApplicationRequest {
	s := DescribeApplicationRequest{}
	s.name = name
	return &s
}
