// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateExternalFunctionRequest(
	name SchemaObjectIdentifier,
	ResultDataType DataType,
	As string,
) *CreateExternalFunctionRequest {
	s := CreateExternalFunctionRequest{}
	s.name = name
	s.ResultDataType = ResultDataType
	s.As = As
	return &s
}

func (s *CreateExternalFunctionRequest) WithOrReplace(OrReplace *bool) *CreateExternalFunctionRequest {
	s.OrReplace = OrReplace
	return s
}

func (s *CreateExternalFunctionRequest) WithSecure(Secure *bool) *CreateExternalFunctionRequest {
	s.Secure = Secure
	return s
}

func (s *CreateExternalFunctionRequest) WithArguments(Arguments []ExternalFunctionArgumentRequest) *CreateExternalFunctionRequest {
	s.Arguments = Arguments
	return s
}

func (s *CreateExternalFunctionRequest) WithReturnNullValues(ReturnNullValues *ReturnNullValues) *CreateExternalFunctionRequest {
	s.ReturnNullValues = ReturnNullValues
	return s
}

func (s *CreateExternalFunctionRequest) WithNullInputBehavior(NullInputBehavior *NullInputBehavior) *CreateExternalFunctionRequest {
	s.NullInputBehavior = NullInputBehavior
	return s
}

func (s *CreateExternalFunctionRequest) WithReturnResultsBehavior(ReturnResultsBehavior *ReturnResultsBehavior) *CreateExternalFunctionRequest {
	s.ReturnResultsBehavior = ReturnResultsBehavior
	return s
}

func (s *CreateExternalFunctionRequest) WithComment(Comment *string) *CreateExternalFunctionRequest {
	s.Comment = Comment
	return s
}

func (s *CreateExternalFunctionRequest) WithApiIntegration(ApiIntegration *AccountObjectIdentifier) *CreateExternalFunctionRequest {
	s.ApiIntegration = ApiIntegration
	return s
}

func (s *CreateExternalFunctionRequest) WithHeaders(Headers []ExternalFunctionHeaderRequest) *CreateExternalFunctionRequest {
	s.Headers = Headers
	return s
}

func (s *CreateExternalFunctionRequest) WithContextHeaders(ContextHeaders []ExternalFunctionContextHeaderRequest) *CreateExternalFunctionRequest {
	s.ContextHeaders = ContextHeaders
	return s
}

func (s *CreateExternalFunctionRequest) WithMaxBatchRows(MaxBatchRows *int) *CreateExternalFunctionRequest {
	s.MaxBatchRows = MaxBatchRows
	return s
}

func (s *CreateExternalFunctionRequest) WithCompression(Compression *string) *CreateExternalFunctionRequest {
	s.Compression = Compression
	return s
}

func (s *CreateExternalFunctionRequest) WithRequestTranslator(RequestTranslator *SchemaObjectIdentifier) *CreateExternalFunctionRequest {
	s.RequestTranslator = RequestTranslator
	return s
}

func (s *CreateExternalFunctionRequest) WithResponseTranslator(ResponseTranslator *SchemaObjectIdentifier) *CreateExternalFunctionRequest {
	s.ResponseTranslator = ResponseTranslator
	return s
}

func NewExternalFunctionArgumentRequest(
	ArgName string,
	ArgDataType DataType,
) *ExternalFunctionArgumentRequest {
	s := ExternalFunctionArgumentRequest{}
	s.ArgName = ArgName
	s.ArgDataType = ArgDataType
	return &s
}

func NewExternalFunctionHeaderRequest(
	Name string,
	Value string,
) *ExternalFunctionHeaderRequest {
	s := ExternalFunctionHeaderRequest{}
	s.Name = Name
	s.Value = Value
	return &s
}

func NewExternalFunctionContextHeaderRequest() *ExternalFunctionContextHeaderRequest {
	return &ExternalFunctionContextHeaderRequest{}
}

func (s *ExternalFunctionContextHeaderRequest) WithContextFunction(ContextFunction string) *ExternalFunctionContextHeaderRequest {
	s.ContextFunction = ContextFunction
	return s
}
