// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateNetworkRuleRequest(
	name SchemaObjectIdentifier,
) *CreateNetworkRuleRequest {
	s := CreateNetworkRuleRequest{}
	s.name = name
	return &s
}

func (s *CreateNetworkRuleRequest) WithOrReplace(OrReplace *bool) *CreateNetworkRuleRequest {
	s.OrReplace = OrReplace
	return s
}

func (s *CreateNetworkRuleRequest) WithNetworkIdentifierType(NetworkIdentifierType *NetworkIdentifierType) *CreateNetworkRuleRequest {
	s.NetworkIdentifierType = NetworkIdentifierType
	return s
}

func (s *CreateNetworkRuleRequest) WithNetworkIdentifiers(NetworkIdentifiers []NetworkIdentifierRequest) *CreateNetworkRuleRequest {
	s.NetworkIdentifiers = NetworkIdentifiers
	return s
}

func (s *CreateNetworkRuleRequest) WithNetworkRuleMode(NetworkRuleMode *NetworkRuleMode) *CreateNetworkRuleRequest {
	s.NetworkRuleMode = NetworkRuleMode
	return s
}

func (s *CreateNetworkRuleRequest) WithComment(Comment *string) *CreateNetworkRuleRequest {
	s.Comment = Comment
	return s
}

func NewNetworkIdentifierRequest() *NetworkIdentifierRequest {
	return &NetworkIdentifierRequest{}
}

func (s *NetworkIdentifierRequest) WithValue(Value string) *NetworkIdentifierRequest {
	s.Value = Value
	return s
}
