// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateSequenceRequest(
	name SchemaObjectIdentifier,
) *CreateSequenceRequest {
	s := CreateSequenceRequest{}
	s.name = name
	return &s
}

func (s *CreateSequenceRequest) WithOrReplace(OrReplace *bool) *CreateSequenceRequest {
	s.OrReplace = OrReplace
	return s
}

func (s *CreateSequenceRequest) WithIfNotExists(IfNotExists *bool) *CreateSequenceRequest {
	s.IfNotExists = IfNotExists
	return s
}

func (s *CreateSequenceRequest) WithWith(With *bool) *CreateSequenceRequest {
	s.With = With
	return s
}

func (s *CreateSequenceRequest) WithStart(Start *int) *CreateSequenceRequest {
	s.Start = Start
	return s
}

func (s *CreateSequenceRequest) WithIncrement(Increment *int) *CreateSequenceRequest {
	s.Increment = Increment
	return s
}

func (s *CreateSequenceRequest) WithValuesBehavior(ValuesBehavior *ValuesBehavior) *CreateSequenceRequest {
	s.ValuesBehavior = ValuesBehavior
	return s
}

func (s *CreateSequenceRequest) WithComment(Comment *string) *CreateSequenceRequest {
	s.Comment = Comment
	return s
}

func NewShowSequenceRequest() *ShowSequenceRequest {
	return &ShowSequenceRequest{}
}

func (s *ShowSequenceRequest) WithLike(Like *Like) *ShowSequenceRequest {
	s.Like = Like
	return s
}

func (s *ShowSequenceRequest) WithIn(In *In) *ShowSequenceRequest {
	s.In = In
	return s
}

func NewDescribeSequenceRequest(
	name SchemaObjectIdentifier,
) *DescribeSequenceRequest {
	s := DescribeSequenceRequest{}
	s.name = name
	return &s
}

func NewDropSequenceRequest(
	name SchemaObjectIdentifier,
) *DropSequenceRequest {
	s := DropSequenceRequest{}
	s.name = name
	return &s
}

func (s *DropSequenceRequest) WithIfExists(IfExists *bool) *DropSequenceRequest {
	s.IfExists = IfExists
	return s
}
