// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateStreamlitRequest(
	name SchemaObjectIdentifier,
	RootLocation string,
	MainFile string,
) *CreateStreamlitRequest {
	s := CreateStreamlitRequest{}
	s.name = name
	s.RootLocation = RootLocation
	s.MainFile = MainFile
	return &s
}

func (s *CreateStreamlitRequest) WithOrReplace(OrReplace *bool) *CreateStreamlitRequest {
	s.OrReplace = OrReplace
	return s
}

func (s *CreateStreamlitRequest) WithIfNotExists(IfNotExists *bool) *CreateStreamlitRequest {
	s.IfNotExists = IfNotExists
	return s
}

func (s *CreateStreamlitRequest) WithWarehouse(Warehouse *AccountObjectIdentifier) *CreateStreamlitRequest {
	s.Warehouse = Warehouse
	return s
}

func (s *CreateStreamlitRequest) WithComment(Comment *string) *CreateStreamlitRequest {
	s.Comment = Comment
	return s
}

func NewAlterStreamlitRequest(
	name SchemaObjectIdentifier,
) *AlterStreamlitRequest {
	s := AlterStreamlitRequest{}
	s.name = name
	return &s
}

func (s *AlterStreamlitRequest) WithIfExists(IfExists *bool) *AlterStreamlitRequest {
	s.IfExists = IfExists
	return s
}

func (s *AlterStreamlitRequest) WithSet(Set *StreamlitsSetRequest) *AlterStreamlitRequest {
	s.Set = Set
	return s
}

func (s *AlterStreamlitRequest) WithRenameTo(RenameTo *SchemaObjectIdentifier) *AlterStreamlitRequest {
	s.RenameTo = RenameTo
	return s
}

func NewStreamlitsSetRequest(
	RootLocation *string,
	MainFile *string,
) *StreamlitsSetRequest {
	s := StreamlitsSetRequest{}
	s.RootLocation = RootLocation
	s.MainFile = MainFile
	return &s
}

func (s *StreamlitsSetRequest) WithWarehouse(Warehouse *AccountObjectIdentifier) *StreamlitsSetRequest {
	s.Warehouse = Warehouse
	return s
}

func (s *StreamlitsSetRequest) WithComment(Comment *string) *StreamlitsSetRequest {
	s.Comment = Comment
	return s
}
