name: release-please
on:
  push:
    branches:
      - 'cgo-enabled-test'

jobs:
  release-please:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run GoReleaser for linux
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config .goreleaser.yml --rm-dist --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
