name: release-please
on:
  push:
    tags:
      - '*'

jobs:
  release-please:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Run GoReleaser for linux
        if: matrix.os == 'ubuntu-latest'
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config .goreleaser.yml --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser for windows
        if: matrix.os == 'windows-latest'
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config .goreleaser-windows.yml --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser for darwin
        if: matrix.os == 'macos-latest'
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config .goreleaser-darwin.yml --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
